SELECT TOP (100) [Customer_ID]
,[Name]
,[Address]
,[Email]
,[Phone_Number]
,[Account_Type]
,[Account_Status]
,[Account_ID]
,[Balance]
,[Account_Creation_Date]
,[Interest_Rate]
,[Transaction_ID]
,[Date_and_Time]
,[Transaction_Type]
,[Amount]
,[Currency]
,[Location]
,[Merchant_Category]
,[Product_ID]
 FROM [dbo].[Fact1]